(WIP) refs #18 ボウリングのスコア計算プログラムを作成
asya81/ruby-practices pull request #19
Opened 2022-07-31 07:27 UTC by asya81

refs #18 ボウリングのスコア計算プログラムを作成中です。

2022-08-04 03:37 UTC, func09 commented on 04.bowling/bowling.rb
> +scores.each { |s| shots << (s == 'X' ? 10 : s.to_i) }
👍

2022-08-04 03:37 UTC, func09 commented on 04.bowling/bowling.rb
> +  end
ここのロジックが難しかったです。処理の意図を説明してもらっても良いでしょうか？
next_frame が 0, 1, 2 が意味するところがよくわからなかったので、特にその辺りを説明してもらえると助かります 🙏

2022-08-06 14:53 UTC, asya81 commented on 04.bowling/bowling.rb
> +  end
`point` は計算結果のスコアの値、`frame` は現在何フレーム目か？
`next_frame`は次のフレームまでの投数を表しています。

例えば、ストライクの場合、1投でそのフレームが終わるため、
次のフレームが始まるのは1投後（`next_frame` = 1）となります。

ストライク以外（スペアまたはオープンフレーム）の場合は、
次のフレームが始まるのが2投後(`next_frame` = 2)になります。

3投ずつをセットにして、フレーム毎にスコアの計算をするために、
ストライク以外の場合は、次のショットをスキップする必要があり、
そのために`next_frame`を導入しました。

こちらでご説明になっていますでしょうか？
他に書き方が思いつかず、こういう書き方にしましたが、
もっと他によい書き方があれば教えていただけると嬉しいです。

2022-08-08 09:46 UTC, func09 requested changes
ロジックの意図がわかったので LGTM とさせていただきます！

2022-08-08 09:46 UTC, func09 commented on 04.bowling/bowling.rb
> +  end
> next_frameは次のフレームまでの投数を表しています。

なるほどー、よくわかりました！ `next_frame` から 「次のフレームまでの投数」の役割が思い当たりませんでした。
素直に変数名を定義するなら

* shot_count_until_next_frame
* current_frame_shots_size

みたいに、具体性を上げてあげるか、ちょっと計算に使いたいだけの変数ですし
そこまでこだわらなくてもいいので

```ruby
next_frame = 0 # 次のフレームまでの投数
```

とコメントされていれば、理解できたと思いました。

2022-08-08 09:56 UTC, func09 approved these changes
approved し忘れてました 🙏 

こちらはマージしちゃってください！

2022-08-08 12:39 UTC, asya81 commented on 04.bowling/bowling.rb
> +  end
ご確認いただき、ありがとうございます〜。
@func09 さんに指摘いただいてご説明する中で、`next_frame`という変数名ではその実体を表せていないなと感じていました。

とはいえ、どんな変数名にすればいいか思いつかなかったので、変数名の案をいただけて、とてもありがたいです🙏
なるほど！そういう名付け方をすればいいのか、と勉強になりました。

`current_frame_shots_size`で書き直してみます。ありがとうございます！

2022-10-25 14:26 UTC, asya81 commented on 04.bowling/bowling.rb
> +  end
遅くなりましたが、コメントで説明を追記する形でレビュー指摘事項を反映しました。

2022-10-25 14:26 UTC, merged